### PR TITLE
docs(README.md) improve readability of docs

### PR DESCRIPTION
**Pull request by d2s**
- Convert document structure to Markdown format.
- Improve readability with clear visual structure.

More details about Markdown syntax:
- https://help.github.com/articles/markdown-basics/
- https://guides.github.com/features/mastering-markdown/
- https://daringfireball.net/projects/markdown/syntax

### CODE REVIEW

**Comment by d2s** [comment]
Updated layout of `README.md` can be seen at [my fork of the repository](https://github.com/d2s/ASTE-Prototype/tree/d2s-docs-readme-improvement#aste-prototype).

**Comment by aripalo** [comment]
:+1: 

Using proper (Github flavoured Markdown) formatting and structure makes the project much more approachable.

**Comment by d2s** [comment]
Ugh... @ToniIltanen apparently just had made a [Git commit](https://github.com/aste-hsc/ASTE-Prototype/commit/5a935242dd4ca22bbc2bf6379d72740b79bf26ee) that made my Pull Request non-mergeable (even while this has much more typographic and structural details). :(

**Comment by ToniIltanen** [comment]
Ahh it seems you beat me to it :+1: 
I added some markups just now, to the Readme. Check it out, it should be slightly better now for a temporary installing guide (at least until i gather some more properly made documents to the repository)

**Comment by d2s** [comment]
I should probably copy your changes to my fork to make this pull request possible to merge.

**Comment by ToniIltanen** [comment]
Yeah, sorry for the mess up, i was not expecting any pull requests at this point while fixing the Readme, and that one caught me off guard :)

**Comment by d2s** [comment]
So you did not take the changes from this, and just closed the pull request?

I didn't have time to look for this yesterday or today…

**Comment by ToniIltanen** [comment]
I couldn't take them, I only had an message about a conflict, waiting for resolving. I'll reopen the pull request for re-handling.

**Comment by d2s** [comment]
Now this branch is up-to-date with the base branch, it is possible to merge it to `master`.

You can preview the updated version at URL:
https://github.com/d2s/ASTE-Prototype/tree/d2s-docs-readme-improvement#aste-prototype

[screenshot from 2015-12-06 20 32 46 github aste-prototype readme md improvement snippet](https://github.com/d2s/ASTE-Prototype/tree/d2s-docs-readme-improvement#aste-prototype)

---

Edited the Markdown syntax in [Atom](https://atom.io/) text editor, together with [Markdown Preview Plus (MPP)](https://atom.io/packages/markdown-preview-plus) package.

screenshot from 2015-12-06 20 17 07 atom editor - editing aste-prototype readme markdown

**Comment by ToniIltanen** [comment]
Good job!

**Comment by d2s** [comment]
It took some effort, but end result is much more readable. Just remember to conform to the Markdown syntax in the future, to make it easier to read for potential contributors.

More details about Markdown syntax:
- https://help.github.com/articles/markdown-basics/
- https://guides.github.com/features/mastering-markdown/
- https://daringfireball.net/projects/markdown/syntax

**Pull request merged**
